server:
  port: 4010

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4011
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # Route for /api/snippet/** to snippet-service
            - id: snippet-service-route
              uri: http://snippet-service:4001
              predicates:
                - Path=/api/snippet/**
              filters:
                - StripPrefix=1
                - JwtValidation
